### ISSUE TITLE
Should we really open links in new tabs?

### ISSUE THREAD

**Issue by markotoplak** [biolab/scorange-hugo#56]
Isn't the best practice to leave the default link behavior alone?

https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by ajdapretnar** [comment]
I agree and disagree. :D I don't like how the user is thrown out of the Orange page to YouTube. If I am just browsing, I would in general like to stay on that page. Of course, I am open to alternatives.

**Comment by ajdapretnar** [comment]
I don't know. Actually, quite some people disagree with this post as seen from the comments. I don't know, really. I agree with the last guy, who gets frustrated when taken to a new site and then wants to go back to the previous site, doesn't know how and get a blank space without the original site. I would prefer new tabs, really.

**Comment by markotoplak** [comment]
I do not like browsers being smarter than me. On the current Quasar page (https://quasar.codes) I therefore made all links raw.

I'd suggest to use it only when absolutely necessary  I won't bug with this anymore. Feel free to close when you want...

**Comment by ajdapretnar** [comment]
First of all, I really love how this page is coming along! 👏 Kudos!
Secondly, you don't have many external links. I don't know. It just looks strange to me when I am suddenly redirected to YouTube.
I do agree, however, this might be counter intuitive.
@irgolic Any thoughts?

**Comment by irgolic** [comment]
Thanks for linking that article @markotoplak, great read.
It's a topic of endless discussion, especially because most of the arguments revolve around the use of conventions. 

For me, it feels intuitive for external links to open in a new tab. Anything that would take you outside of the website's ecosystem (the header/footer links present on each page) should behave as if it's branching away from the 'home' tab.

On the other hand, I expect a search engine to open links in the same tab -- 90% of the time I use Google I find what I need on my first click. When _browsing_ a website (such as Orange), it will likely take you more tries to find the content you're looking for.

**Comment by ajdapretnar** [comment]
I don't have a 'correct' answer to this, but I understand the previous comment as in favour of external links opening in a new tab, so let's go with that... We can change this if we find out we made a mistake at any time.
